package Vista;

import Controlador.SimulacionControl.SimulacionControl;
import Modelo.TipoTramite;
import Vista.Tabla.ModeloTablaTramite;
import Vista.Util.UtilVista;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEJANDRO
 */
public class Iees extends javax.swing.JFrame {

    private SimulacionControl simulControl = new SimulacionControl();
    private ModeloTablaTramite mtp = new ModeloTablaTramite();
    private ModeloTablaTramite mtp1 = new ModeloTablaTramite();
    private ModeloTablaTramite mtp2 = new ModeloTablaTramite();
    private Integer personasTotal = 0;
    private Integer tiempoTotal = 0;

    /**
     * Creates new form Iees
     */
    public Iees() {
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();

        CargarTabla();
    }

    private void CargarTabla() {
        cbxProcesos.setSelectedIndex(-1);
        tblVen1.setModel(mtp);
        tblVen1.updateUI();
        tblVen2.setModel(mtp1);
        tblVen2.updateUI();
        tblVen3.setModel(mtp2);
        tblVen3.updateUI();
        txtDuracion.setText(" ");
        txtVentanilla.setText(" ");

    }

    private void Limpiar() {
        try {
            UtilVista.CargarVentanillaL(cbxProcesos);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        txtDuracion.setText(" ");
        txtVentanilla.setText(" ");
        txtPersonas.setText(" ");
        tblVen1.clearSelection();
        tblVen2.clearSelection();
        tblVen3.clearSelection();
        CargarTabla();
        simulControl.setSimulacion1(null);
    }

    private Boolean Validar() {
        return (!txtDuracion.getText().trim().isEmpty()
                && !txtVentanilla.getText().trim().isEmpty());
    }

    private void Guardar() {
        if (Validar()) {

            simulControl.getSimulacion1().setDuracionTiempo(tiempoTotal);
            simulControl.getSimulacion1().setNro_personas(personasTotal);
            simulControl.getSimulacion1().setNombre(UtilVista.ObtenerVentanilla(cbxProcesos));

            if (simulControl.persist()) {

            } else {
               
            }

            JOptionPane.showMessageDialog(null, "Datos generados y guardados con éxito");
            CargarTabla();
            Limpiar();

        } else {
            JOptionPane.showMessageDialog(null, "Falta llenar campos");
        }
    }

    private void generarDatosAleatorios(Integer tabla) {
        cbxProcesos.removeAllItems();
        Random random = new Random();
        int numeroPersonas = random.nextInt(6) + 15;
        personasTotal = numeroPersonas + personasTotal;
        String proceso;
        String[] procesos = {"Cambio de clave", "Actualización de datos", "Asignación de afiliados", "Recuperación de clave"};
        for (int i = 0; i < numeroPersonas; i++) {
            TipoTramite t = new TipoTramite();
            proceso = procesos[random.nextInt(procesos.length)];
            int duracion = 0;
            switch (proceso) {
                case "Cambio de clave":
                    duracion = 4;
                    break;
                case "Actualización de datos":
                    duracion = 7;
                    break;
                case "Asignación de afiliados":
                    duracion = 15;
                    break;
                case "Recuperación de clave":
                    duracion = 3;
                    break;
            }
            tiempoTotal = duracion + tiempoTotal;
            cbxProcesos.addItem(proceso);
            txtDuracion.setText(Integer.toString(duracion));
            txtPersonas.setText(Integer.toString(numeroPersonas));
            t.setId(i);
            t.setDuracion(duracion);
            t.setNombre(proceso);
            if (tabla == 1) {
                mtp.getTramites().add(t);
            } else if (tabla == 2) {
                mtp1.getTramites().add(t);
            } else {
                mtp2.getTramites().add(t);
            }
            t = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVen1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVen2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVen3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        txtVentanilla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxProcesos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPersonas = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVen1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVen1);

        tblVen2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVen2);

        tblVen3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblVen3);

        jLabel5.setText("IEES");

        btnGenerar.setText("Generar Datos");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtVentanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentanillaActionPerformed(evt);
            }
        });
        txtVentanilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVentanillaKeyTyped(evt);
            }
        });

        jLabel2.setText("Id ventanilla:");

        jLabel3.setText("Duracion ventanilla");

        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });
        txtDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuracionKeyTyped(evt);
            }
        });

        jLabel6.setText("Descripcion:");

        cbxProcesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Numero Personas:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Listas Simulaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(btnGenerar))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbxProcesos, 0, 181, Short.MAX_VALUE)
                                        .addComponent(txtVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDuracion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnGuardar)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnGuardar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVentanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentanillaActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        generarDatosAleatorios(1);
        generarDatosAleatorios(2);
        generarDatosAleatorios(3);

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtVentanillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVentanillaKeyTyped
        char c = evt.getKeyChar();

        // Verifica si el caracter es un dígito
        if (!Character.isDigit(c)) {
            evt.consume();  // Si no es un dígito, consume el evento para ignorarlo
        }
    }//GEN-LAST:event_txtVentanillaKeyTyped

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void txtDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionKeyTyped
        char c = evt.getKeyChar();

        // Verifica si el caracter es un dígito
        if (!Character.isDigit(c)) {
            evt.consume();  // Si no es un dígito, consume el evento para ignorarlo
        }
    }//GEN-LAST:event_txtDuracionKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new simulaciones().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxProcesos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblVen1;
    private javax.swing.JTable tblVen2;
    private javax.swing.JTable tblVen3;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtPersonas;
    private javax.swing.JTextField txtVentanilla;
    // End of variables declaration//GEN-END:variables
}
